### ISSUE TITLE
Character and Layout Confidence

### ISSUE THREAD

**Issue by muhdzubair** [ExtractTable/ExtractTable-py#13]
Hi, need some definition material for Character and Layout Confidence like how it is calculated mathematically using below code. Thanks.

```python
for idx, each_table in enumerate(et_sess.ServerResponse.json()['Tables']):
    print("CharacterConfidence = ", each_table['CharacterConfidence'])
    print("LayoutConfidence = ", each_table['LayoutConfidence'])
```

**Comment by akshowhini** [comment]
**Character Confidence** (scored between 0-100) determines the average accuracy of all character recognised in the table. Usually, a **type-written** font comes with >95 score, while >80 on the **handwritten** ones are inferred good.

**Layout Confidence** (scored between 0-100) is basically the machine's heuristic in determining the layout of the table. Consider it as how good the characters alignment are recognised. Our observation shows 
- 80-100 :  **Perfect**
- 70-80 :  **Close to Perfect**
- 60-70 : **Almost There** - issues detecting the table ends. eg. Multi-column table but only one "Total" column in the last row
- 50-60 : **Confused** - usually on "middle aligned" multi lined columns
- <50 : Human attention needed


<ins>Note</ins>: Both confidence scores are calculated at the table level.

**Comment by akshowhini** [comment]
**Character Confidence** (scored between 0-100) determines the average accuracy of all character recognized in the table. Usually, a **type-written** font comes with >95 score, while >80 on the **handwritten** ones are inferred good.

**Layout Confidence** (scored between 0-100) is the machine's heuristic in determining the layout of the table. Consider it as to how good the characters alignment is recognized. Our observation shows 
- 80-100:  **Perfect**
- 70-80:  **Close to Perfect**
- 60-70: **Almost There** - issues detecting the table ends. eg. Multi-column table but only one "Total" column in the last row
- 50-60: **Confused** - usually on "middle aligned" multi-lined columns
- <50: Human attention needed


<ins>Note</ins>: Both confidence scores are calculated at the table level.
