### ISSUE TITLE
Is it possible to  get the data in excel by maintaining table structure?

### ISSUE THREAD

**Issue by jcthink** [ExtractTable/ExtractTable-py#27]
**Is your feature request related to a problem? Please describe.**

**Describe alternatives you've considered**

**Describe the solution you'd like** [optional, but helpful]

**Additional context**

**Comment by akshowhini** [comment]
@jcthink The default output of `table_data` is a list of [pandas dataframe](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html). So, it is easy to convert the [dataframe to excel](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_excel.html), and many other formats. 

Sample code below to convert the output to excel

```python 
table_data = et_sess.process_file(filepath=Location_of_PDF_with_Tables, output_format="df", pages="all")

import pandas as pd

with pd.ExcelWriter('output.xlsx') as writer:
	for idx, each_table_df in enumerate(table_data):
		each_table_df.to_excel(writer, sheet_name=f'table_no_{idx+1}')
```
