### ISSUE TITLE
Custom output path when the output_format is csv

### ISSUE THREAD

**Issue by iamTheL** [ExtractTable/ExtractTable-py#33]
**Is your feature request related to a problem? Please describe.**
When the `output_format` is set to `csv` the csv file is written to some random path in `/tmp` location.

**Describe the solution you'd like** [optional, but helpful]
Define a parameter in the `process_file` like `output_file` which takes the absolute path where the file needs to be written along with the file name

**Comment by akshowhini** [comment]
@iamTheL You could use `save_output` of the session object to move the output from the temp location to the desired destination.

```et_sess.save_output(output_folder, output_format="csv")```


You may want to look at "Save Table & Text to LOCAL" in the [tutorial](https://colab.research.google.com/drive/1OlryNyNTOPDttF19_heLNEeLnr_gjDGB#scrollTo=MytCD36ja6KM)
