### ISSUE TITLE
Invalid cross-device link

### ISSUE THREAD

**Issue by Elegye** [ExtractTable/ExtractTable-py#35]
**Describe the bug**
On some OS, we can not save output file to temporary directory (let's say `/tmp`) and move it to a new place. It throws the following error : 
```
os.replace(each_tbl_path, os.path.join(output_folder, input_fname+os.path.basename(each_tbl_path)))
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmp7hqcm0fh/_table_1.csv' -> '/var/www/python/app/tmp/details_table_1.csv'
```
After checking the source code, it appears ExtractTable use `os.replace` to move the file. This method does not support moving file from a partition to an other : https://stackoverflow.com/questions/42392600/oserror-errno-18-invalid-cross-device-link

**To Reproduce**
I use Python 3.6 in a venv.
You will need two different system parts, and invoke save_output from ExtractTable-py library, to save file from a filesystem to an other.
I have not tried, but I think you can simply reproduce this bug by invoking `os.replace` without calling ExtractTable-py.

**Expected behavior**
Move the file from a filesystem to an other. I think using `shutil.move` would be a preferable way to achieve file moving than `os.replace`.

**Comment by akshowhini** [comment]
@Elegye Thanks for reporting the issue. I have just made a pull request to fix this along with couple other features. Hopefully, it gets an approval in the next 24 hours.

**Comment by ExtractTable** [comment]
Hello @Elegye 

Thanks for reporting the issue. Please accept some credits as a token of appreciation.

Regards,
ET-Team
