### ISSUE TITLE
bug: function "et_sess.save_output(output_folder, output_format="csv")" output file, the file name lack some alpha of  the origin full name

### ISSUE THREAD

**Issue by hengfanz** [ExtractTable/ExtractTable-py#44]
**Describe the bug**
my picture name is all suffix png. such as "10.1016@j.ejmech.2019.111849_14-1-4.png"

![image](https://user-images.githubusercontent.com/6941820/137288896-7d280206-e98d-4811-ba15-7e9e375dd692.png)

**To Reproduce**
Steps to reproduce the behavior: or the code you tried

**Expected behavior**

**Additional context**

**Comment by akshowhini** [comment]
We can not recreate the issue. Can you provide the steps to recreate this bug?

**Comment by hengfanz** [comment]
![10 1016@j ejmech 2019 111849_12-1-4](https://user-images.githubusercontent.com/6941820/137690457-95173d06-4723-4492-b13c-8cb9a0a33574.png)
![10 1016@j ejmech 2019 111849_13-1-4](https://user-images.githubusercontent.com/6941820/137690467-8ef1552b-e422-4c86-81f7-87c37c776216.png)
![10 1016@j ejmech 2019 111849_14-1-4](https://user-images.githubusercontent.com/6941820/137690470-8c4c94d9-c43e-461d-b382-3f5458bd74ec.png)
these are three pictures, you can try it again, please notice the picture name,such as "10.1016@j.ejmech.2019.111849_12-1-4.png"

**Comment by akshowhini** [comment]
@hengfanz  Can you please email brain@extracttable.com 

This looks more of image specific issue, rather than the library problem. Thank you
