### ISSUE TITLE
question: what meaning is LayoutConfidence?

### ISSUE THREAD

**Issue by franztao** [ExtractTable/ExtractTable-py#45]
"CharacterConfidence": <float>,             # Average Accuracy of all Characters recognized from the input-page
"LayoutConfidence": <float>,                    ## Accuracy of table layout's design decision
please give out the detaild decription or calculate function code about CharacterConfidence,LayoutConfidence

**Comment by akshowhini** [comment]
Please refer to [this](https://github.com/ExtractTable/ExtractTable-py/issues/13#issuecomment-549424641)
