### ISSUE TITLE
found some bugs and list the bugs out

### ISSUE THREAD

**Issue by franztao** [ExtractTable/ExtractTable-py#47]
**Describe the bug**
1.不能识别出垮列的文本，识别成表格时，不符合逻辑的分开成两边
![image](https://user-images.githubusercontent.com/6941820/139175230-b7d64d6c-b3c0-4481-8b5e-9f4a19ecdeb2.png)
![image](https://user-images.githubusercontent.com/6941820/139175504-90441f23-cf0e-4975-bee0-18aa3a0b158b.png)

2.不能识别加减号,can not recognize Plus minus sign.
31.2 + 4.98
![image](https://user-images.githubusercontent.com/6941820/139175261-9c8cb6a8-18b9-468d-bf8d-0262db1d4ee5.png)
3.不能够识别上下标，can not recognize subscript and supscript.
![image](https://user-images.githubusercontent.com/6941820/139175413-508d031b-cba4-4d7e-abaa-429dc199cedc.png)
4.ocr识别丢失字符  loss some recognized tokens
![image](https://user-images.githubusercontent.com/6941820/139175621-c393ac24-5a15-4a84-8457-4598e16af4e7.png)
5.长的表格，有部分没有识别出来  long size table,can not recognize the bottem part 
![image](https://user-images.githubusercontent.com/6941820/139176894-8cc7ad0b-431b-4106-bb74-f72003fbcaed.png)
![image](https://user-images.githubusercontent.com/6941820/139176991-e73f89be-a242-4081-9ca7-1699d111cb10.png)
6.cell中有化学式的，识别不出来,when there is chemical formulate in cell, can not recognize the table
![image](https://user-images.githubusercontent.com/6941820/139177531-a26631e9-c192-45a9-9904-9745fa19858e.png)

**To Reproduce**
Steps to reproduce the behavior: or the code you tried

**Expected behavior**
I can solve these problems with us. 

**Additional context**

**Comment by hengfanz** [comment]
![image](https://user-images.githubusercontent.com/6941820/139591720-3f997dc6-6f44-436b-b62c-0ae007736c47.png)
![image](https://user-images.githubusercontent.com/6941820/139591725-e6b152b4-c10c-4dfe-90e5-46c18015d884.png)

**Comment by hengfanz** [comment]
![image](https://user-images.githubusercontent.com/6941820/139617099-6794ffcb-711d-48cd-8a96-136cfaf3a3dc.png)
