### ISSUE TITLE
Error: PdfFileReader is deprecated and was removed in PyPDF2 3.0.0. Use PdfReader instead.

### ISSUE THREAD

**Issue by eliaweiss** [ExtractTable/ExtractTable-py#51]
**Describe the bug**
Receive
Error: PdfFileReader is deprecated and was removed in PyPDF2 3.0.0. Use PdfReader instead.
When parsing pdf file

{"errorMessage": "PdfFileReader is deprecated and was removed in PyPDF2 3.0.0. Use PdfReader instead.", "errorType": "DeprecationError", "stackTrace": ["  File \"/var/task/app.py\", line 32, in lambda_handler\n    return handleOcrTable(event, context)\n", "  File \"/var/task/handlers/handleOcrTable.py\", line 183, in handleOcrTable\n    return tableParse(inputData, event)\n", "  File \"/var/task/handlers/handleOcrTable.py\", line 57, in tableParse\n    table_data_res = et_sess.process_file(filepath=path, output_format=\"df\", pages=\"1\")\n", "  File \"/var/task/ExtractTable/__init__.py\", line 178, in process_file\n    with PrepareInput(filepath, pages=pages) as infile:\n", "  File \"/var/task/ExtractTable/FileOperations/__init__.py\", line 55, in __init__\n    self.filepath = self.pdf_separator(gather_pages)\n", "  File \"/var/task/ExtractTable/FileOperations/__init__.py\", line 61, in pdf_separator\n    pdf_reader = PyPDF2.PdfFileReader(self.filepath)\n", "  File \"/var/task/PyPDF2/_reader.py\", line 1974, in __init__\n    deprecation_with_replacement(\"PdfFileReader\", \"PdfReader\", \"3.0.0\")\n", "  File \"/var/task/PyPDF2/_utils.py\", line 369, in deprecation_with_replacement\n    deprecation(DEPR_MSG_HAPPENED.format(old_name, removed_in, new_name))\n", "  File \"/var/task/PyPDF2/_utils.py\", line 351, in deprecation\n    raise DeprecationError(msg)\n"]}

**To Reproduce**
Steps to reproduce the behavior: or the code you tried

**Expected behavior**

**Additional context**

**Comment by erikkallen** [comment]
I have the same issue

**Comment by akshowhini** [comment]
The issue seems to be with the latest PyPDF2 update. Downgrade the PyPDF2 version to 2.12.1

`pip install ExtractTable`

`pip install PyPDF2==2.12.1`
